export interface InfoMedica {
    peso_aproximado: number,
      embarazo: boolean,
      cardiaco: boolean,
      taquicardia: boolean,
      hipertiroidismo: boolean,
      extrasistole: boolean,
      fatiga: boolean,
      convulsiones: boolean,
      vertigo: boolean,
      cadera: boolean,
      psiquiatria: boolean,
      diabetes: boolean,
      cirugia: boolean,
      factor_rh: string,
      eps: string,
      medico: string,
      fractura: boolean,
      arl: string,
      nombre_emergencia1: string,
      celular_emer1: string,
      nombre_emergencia2: string,
      celular_emer2: string
}
